name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Dependencies
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Update dependencies
        run: |
          npx npm-check-updates -u
          npm install

      - name: Run tests
        run: |
          npm run test:unit
          npm run type-check
          npm run lint

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            This is an automated pull request to update project dependencies.
            
            ## Changes
            - Updated all dependencies to their latest versions
            - All tests are passing
            
            Please review the changes and merge if everything looks good.
          branch: chore/update-dependencies
          delete-branch: true
